# Generated by Django 4.1.2 on 2022-10-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='correct',
            new_name='greenBugs',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='predictions',
            new_name='redBugs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gain',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loss',
        ),
        migrations.AddField(
            model_name='profile',
            name='userBugs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='userCompletedBugs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='yellowBugs',
            field=models.IntegerField(default=0),
        ),
    ]
