# Generated by Django 4.1.2 on 2022-10-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='home',
            new_name='severity',
        ),
    ]
