# Generated by Django 4.1.2 on 2022-11-06 22:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0002_bug_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='Users',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.ImageField(default='default.jpg', upload_to='files')),
                ('bug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bugs.bug')),
            ],
        ),
    ]
