# Generated by Django 4.1.2 on 2022-11-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_alter_bug_users_alter_bug_severity_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.bug'),
        ),
    ]
