# Generated by Django 4.1.2 on 2022-11-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_alter_file_bug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
