# Generated by Django 4.1.2 on 2022-10-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_alter_bug_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
