# Generated by Django 4.1.2 on 2022-11-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_file_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploader',
        ),
    ]
