# Generated by Django 4.1.2 on 2022-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0010_alter_comment_author_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.ImageField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
