# Generated by Django 4.1.2 on 2022-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0011_comment_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='pic',
            field=models.ImageField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
